/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as PageIdIndexRouteImport } from './routes/$pageId/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppEditIndexRouteImport } from './routes/app/edit/index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const PageIdIndexRoute = PageIdIndexRouteImport.update({
  id: '/$pageId/',
  path: '/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEditIndexRoute = AppEditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/$pageId/': typeof PageIdIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/edit/': typeof AppEditIndexRoute
}
export interface FileRoutesByTo {
  '/app/dashboard': typeof AppDashboardRoute
  '/$pageId': typeof PageIdIndexRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/app/edit': typeof AppEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/$pageId/': typeof PageIdIndexRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/edit/': typeof AppEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/app' | '/app/dashboard' | '/$pageId/' | '/app/' | '/app/edit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/dashboard' | '/$pageId' | '/' | '/app' | '/app/edit'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/app/dashboard'
    | '/$pageId/'
    | '/_site/'
    | '/app/'
    | '/app/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  PageIdIndexRoute: typeof PageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$pageId/': {
      id: '/$pageId/'
      path: '/$pageId'
      fullPath: '/$pageId/'
      preLoaderRoute: typeof PageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/edit/': {
      id: '/app/edit/'
      path: '/edit'
      fullPath: '/app/edit/'
      preLoaderRoute: typeof AppEditIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditIndexRoute: typeof AppEditIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditIndexRoute: AppEditIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  PageIdIndexRoute: PageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
